### ISSUE TITLE
Comentarios sobre red social sprint 1

### ISSUE THREAD

**Issue by Jonhks** [alppacat/cdmx-2018-06-bc-core-am-social-network#19]
@CitlalliDMG , @GenesisMauries, @alppacat.
- Que es el archivo .vscode?
- En un proyecto lo más correcto es que solo exista un README.md. 
- Buena distribución de responsabilidades de archivos, solo me preocupa que puedan explicar lo que pasa en todo el código. 
- Podrían intentar pasar todo el js Es5 a Es6.
- Recuerden tener en cuenta y hacer código enfocado a Test, con esto me refiero a la separación de responsabilidades de los archivos js y hacer las funciones puras para poder testearlas.
- Les dejo un link que habla sobre TDD, espero les sirva https://medium.com/javascript-scene/5-common-misconceptions-about-tdd-unit-tests-863d5beb3ce9.
 - Chicas van por muy buen camino, sigan así y nunca dejen de aprender ni se den por vencidas! 😃

**Comment by alppacat** [comment]
Gracias por el feedback!  estaremos trabajando en las observaciones dadas!

**Comment by GenesisMauries** [comment]
Ya estamos trabajando en los issues, gracias por la retroalimentación.  :metal:  :muscle:

**Comment by CitlalliDMG** [comment]
@Jonhks  ¡Gracias por el feedback!
El archivo .vscode fue error mio, al parecer tiene que ver con las configuraciones de mi VS Code, pero olvide meterlo al gitignore.
Estamos trabajando para integrar las observaciones que nos hiciste 😃
